<?php
// HTpost 3.0 beta 1
// HTpost-settings.php
// *** DO NOT edit this file manually. Log in to HTpost, go to Administrative Options, and choose Setup HTpost.

$HTpost_settings["display_cutoff"] = "4";
$HTpost_settings["session_timeout"] = "4";
$HTpost_settings["output_xml"] = "false";
$HTpost_settings["daily_header"] = "true";
$HTpost_settings["daily_header_template"] = "<h1>{{daily_header}}</h1>";
$HTpost_settings["path_main"] = "../news.php";
$HTpost_settings["path_main_template"] = "templates/news.htpost";
$HTpost_settings["path_template"] = "templates/post.htpost";
$HTpost_settings["path_xml_output"] = "../feed.xml";
$HTpost_settings["path_xml_template"] = "templates/template.xml";
$HTpost_settings["redirect_url"] = "../news.php";
$HTpost_settings["date_individual"] = "j F, Y";
$HTpost_settings["time_individual"] = "g:i a";
$HTpost_settings["date_daily"] = "l, F j Y";
$HTpost_settings["DB_hostname"] = "localhost";
$HTpost_settings["DB_username"] = "will";
$HTpost_settings["DB_password"] = "will";
$HTpost_settings["DB_database"] = "HTpost";
$HTpost_settings["DB_post_table"] = "posts";
$HTpost_settings["DB_security_table"] = "security";
$HTpost_settings["admin_name"] = "will";
$HTpost_settings["admin_password"] = "will";
$HTpost_settings["admin_email"] = "will@horcob.org";
$HTpost_settings["admin_image"] = "";
$HTpost_settings["HTpost_version"] = "3.0 beta 1";
$HTpost_settings["email"] = "no email";

?>